name: Build And Deploy

on:
  push:
    branches:
    - "**"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 18

    - name: Install dependencies
      run: npm install

    - name: Replace placeholders in environment.ts
      run: |
          sed -i "s/\${API_KEY}/${{ secrets.API_KEY }}/g" src/environments/environment.ts
          sed -i "s/\${AUTH_DOMAIN}/${{ secrets.AUTH_DOMAIN }}/g" src/environments/environment.ts
          sed -i "s/\${PROJECT_ID}/${{ secrets.PROJECT_ID }}/g" src/environments/environment.ts
          sed -i "s/\${STORAGE_BUCKET}/${{ secrets.STORAGE_BUCKET }}/g" src/environments/environment.ts
          sed -i "s/\${MESSAGING_SENDER_ID}/${{ secrets.MESSAGING_SENDER_ID }}/g" src/environments/environment.ts
          sed -i "s/\${APP_ID}/${{ secrets.APP_ID }}/g" src/environments/environment.ts

    - name: Display contents of environment.ts after sed
      run: cat src/environments/environment.ts

    - name: Build
      run: npm run build

    - if: ${{ success() && github.ref == 'refs/heads/develop' }}
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: dist/ihmsservicefrontend
        enable_jekyll: true
